# World Happiness Data

In this section of our project we will be taking five separate csvs that were scraped down from a World Happiness database, clean, organize and merge them together; therefore, we can use our new cleaned data to create charts/graphs to visualize happiness measurment over the course of five years.

In [351]:
# Magic Function for graphs/displays
%matplotlib notebook

In [352]:
# Importing our Dependencies
import pandas as pd
import numpy as np


# Hide warning messages in notebook
import warnings
warnings.filterwarnings("ignore")

-----------------------
# Part 1 - Load and Read CSV files

In [353]:
# Take in all of our Happiness data and read it into pandas
H_2015 = "Happiness_Data/2015.csv"
H_2016 = "Happiness_Data/2016.csv"
H_2017 = "Happiness_Data/2017.csv"
H_2018 = "Happiness_Data/2018.csv"
H_2019 = "Happiness_Data/2019.csv"

Happiness_2015 = pd.read_csv(H_2015)
Happiness_2016 = pd.read_csv(H_2016)
Happiness_2017 = pd.read_csv(H_2017)
Happiness_2018 = pd.read_csv(H_2018)
Happiness_2019 = pd.read_csv(H_2019)

---------------------------------------
# Part 2 - Checking Data 

* Checked each year's data before making any changes
* Checked each year's data type, incase we need to change it's type
* Removed unneccessary columns
* Organized each dataframe column's orders

### 2015 Happiness Data

In [354]:
#check happiness data for 2015 before combining
#Happiness_2015.info()

# Removing columns that are extra and unnecessary
pop_col = Happiness_2015.pop("Standard Error")
Happiness_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

### 2016 Happiness Data

In [355]:
#check happiness data for 2016 before combining
#Happiness_2016.info()

# Removing columns that are extra and unnecessary
lower_col = Happiness_2016.pop("Lower Confidence Interval")
upper_col = Happiness_2016.pop( "Upper Confidence Interval")
Happiness_2016.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

### 2017 Happiness Data

In [356]:
#check happiness data for 2017 before combining
#Happiness_2017.info()

# Removing columns that are extra and unnecessary
high_col = Happiness_2017.pop("Whisker.high")
low_col = Happiness_2017.pop( "Whisker.low")

# In Happiness 2017 Data, Generosity and Trust.Gov Corruption had to be switched in order to match our previous years Data
col_name="Generosity"
first_col = Happiness_2017.pop(col_name)
Happiness_2017.insert(8, col_name, first_col)

Happiness_2017

,Country,Happiness.Rank,Happiness.Score,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Trust..Government.Corruption.,Generosity,Dystopia.Residual
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

### 2018 Happiness Data

In [357]:
#check happiness data for 2018 before combining
# Happiness_2018.info()

# In Happiness 2018 Data, Overall Rank and Country column had to be switched in order to match our previous years Data
col_name="Country or region"
first_col = Happiness_2018.pop(col_name)
Happiness_2018.insert(0, col_name, first_col)

# Rename Country or region name for easier merge later
Happiness_2018 = Happiness_2018.rename(columns={"Country or region":"Country"})
Happiness_2018.head()

,Country,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.256,0.357

### 2019 Happiness Data

In [358]:
#check happiness data for 2019 before combining
# Happiness_2019.info()

# In Happiness 2019 Data, Overall Rank and Country column had to be switched in order to match our previous years Data
col_name="Country or region"
first_col = Happiness_2019.pop(col_name)
Happiness_2019.insert(0, col_name, first_col)

# Rename Country or region name for easier merge later
Happiness_2019 = Happiness_2019.rename(columns={"Country or region":"Country"})
Happiness_2019.head()

,Country,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,5,7.488,1.396,1.522,0.999,0.557,0.322,0.298

------------
# Part 3 - Happiness Merging

* We performed four different merges
* Changed column names to organize each dataframe by year

### Merging [ 2015 ] Happiness Data with 2016 Happiness Data

In [359]:
# Merge the first two datasets on "Country" so that no data is lost (should be 182 rows)
combined_happiness = pd.merge(Happiness_2015, Happiness_2016, how='outer', on=['Country', 'Region'])
combined_happiness.head()

,Country,Region,Happiness Rank_x,Happiness Score_x,Economy (GDP per Capita)_x,Family_x,Health (Life Expectancy)_x,Freedom_x,Trust (Government Corruption)_x,Generosity_x,Dystopia Residual_x,Happiness Rank_y,Happiness Score_y,Economy (GDP per Capita)_y,Family_y,Health (Life Expectancy)_y,Freedom_y,Trust (Government Corruption)_y,Generosity_y,Dystopia Residual_y
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2.0,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,3.0,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,1.0,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,4.0,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,6.0,7.404,1.44015,1.09610,0.82760,0.57370,0.31329,0.44834,2.70485

### ReName 2015 & 2016 Columns

In [360]:
# Rename our _x columns to:'2015_Happiness Rank', '2015_Happiness Score', '2015_Economy', '2015_Family', '2015_Health' , '2015_Freedom', '2015_Corruption_Trust', '2015_Generosity', '2015_Dystopia Residual'
                                                          #'very long text\ntext line 2\ntext line 3'                  
combined_happiness = combined_happiness.rename(columns={"Happiness Rank_x":"2015 Happiness Rank", 
                                                        "Happiness Score_x":"2015 Happiness Score", 
                                                        "Economy (GDP per Capita)_x":"2015 Economy", 
                                                        "Family_x": "2015 Family",
                                                        "Health (Life Expectancy)_x":"2015 Health", 
                                                        "Freedom_x":"2015 Freedom",
                                                        "Trust (Government Corruption)_x":"2015 Corruption/Trust", 
                                                        "Generosity_x":"2015 Generosity",
                                                        "Dystopia Residual_x":"2015 Dystopia Residual"})


# Rename our _y columns
combined_happiness = combined_happiness.rename(columns={"Happiness Rank_y":"2016 Happiness Rank", 
                                                        "Happiness Score_y":"2016 Happiness Score", 
                                                        "Economy (GDP per Capita)_y":"2016 Economy", 
                                                        "Family_y": "2016 Family",
                                                        "Health (Life Expectancy)_y":"2016 Health", 
                                                        "Freedom_y":"2016 Freedom",
                                                        "Trust (Government Corruption)_y":"2016 Corruption/Trust", 
                                                        "Generosity_y":"2016 Generosity",
                                                        "Dystopia Residual_y":"2016 Dystopia Residual"})
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,2015 Dystopia Residual,2016 Happiness Rank,2016 Happiness Score,2016 Economy,2016 Family,2016 Health,2016 Freedom,2016 Corruption/Trust,2016 Generosity,2016 Dystopia Residual
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2.0,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,3.0,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,1.0,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,4.0,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,6.0,7.404,1.44015,1.09610,0.82760,0.57370,0.31329,0.44834,2.70485

### Merging  [ 2017 ] Happiness Data with Combined Happiness Data (2015,2016)

In [361]:
# Merge our newly combined dataframe with the 2015 dataframe
combined_happiness = pd.merge(combined_happiness,Happiness_2017, how="outer", on="Country")
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2016 Dystopia Residual,Happiness.Rank,Happiness.Score,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Trust..Government.Corruption.,Generosity,Dystopia.Residual
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,2.69463,4.0,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,2.83137,3.0,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,2.73939,2.0,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,2.66465,1.0,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,2.70485,7.0,7.316,1.479204,1.481349,0.834558,0.611101,0.287372,0.435540,2.187264

### ReName 2017 Columns

In [362]:
# Rename our 2017 columns
combined_happiness = combined_happiness.rename(columns={"Happiness.Rank":"2017 Happiness Rank", 
                                                        "Happiness.Score":"2017 Happiness Score", 
                                                        "Economy..GDP.per.Capita.":"2017 Economy", 
                                                        "Family": "2017 Family",
                                                        "Health..Life.Expectancy.":"2017 Health", 
                                                        "Freedom":"2017 Freedom",
                                                        "Trust..Government.Corruption.":"2017 Corruption/Trust", 
                                                        "Generosity":"2017 Generosity",
                                                        "Dystopia.Residual":"2017 Dystopia Residual"})
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2016 Dystopia Residual,2017 Happiness Rank,2017 Happiness Score,2017 Economy,2017 Family,2017 Health,2017 Freedom,2017 Corruption/Trust,2017 Generosity,2017 Dystopia Residual
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,2.69463,4.0,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,2.83137,3.0,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,2.73939,2.0,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,2.66465,1.0,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,2.70485,7.0,7.316,1.479204,1.481349,0.834558,0.611101,0.287372,0.435540,2.187264

### Merging [ 2018 ] Happiness Data  with Combined Happiness data (2015,2016,2017)

In [363]:
# Merge our newly combined dataframe with the 2018 dataframe
combined_happiness = pd.merge(combined_happiness, Happiness_2018, how="outer", on="Country")
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2017 Generosity,2017 Dystopia Residual,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,0.290549,2.276716,5.0,7.487,1.420,1.549,0.927,0.660,0.256,0.357
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,0.475540,2.322715,4.0,7.495,1.343,1.644,0.914,0.677,0.353,0.138
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,0.355280,2.313707,3.0,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,0.362012,2.277027,2.0,7.594,1.456,1.582,0.861,0.686,0.286,0.340
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,0.435540,2.187264,7.0,7.328,1.330,1.532,0.896,0.653,0.321,0.291

### ReName 2018 Columns

In [364]:
# Rename our 2018 columns
combined_happiness = combined_happiness.rename(columns={"Overall rank":"2018 Happiness Rank", 
                                                        "Score":"2018 Happiness Score", 
                                                        "GDP per capita":"2018 Economy", 
                                                        "Social support": "2018 Family",
                                                        "Healthy life expectancy":"2018 Health", 
                                                        "Freedom to make life choices":"2018 Freedom",
                                                        "Generosity":"2018 Generosity",
                                                        "Perceptions of corruption":"2018 Dystopia Residual"})
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2017 Generosity,2017 Dystopia Residual,2018 Happiness Rank,2018 Happiness Score,2018 Economy,2018 Family,2018 Health,2018 Freedom,2018 Generosity,2018 Dystopia Residual
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,0.290549,2.276716,5.0,7.487,1.420,1.549,0.927,0.660,0.256,0.357
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,0.475540,2.322715,4.0,7.495,1.343,1.644,0.914,0.677,0.353,0.138
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,0.355280,2.313707,3.0,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,0.362012,2.277027,2.0,7.594,1.456,1.582,0.861,0.686,0.286,0.340
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,0.435540,2.187264,7.0,7.328,1.330,1.532,0.896,0.653,0.321,0.291

### Merging [ 2019 ] Happiness Data with Combined Happiness data (2015,2016,2017,2018)

In [365]:
# Merge our newly combined dataframe with the 2018 dataframe
combined_happiness = pd.merge(combined_happiness, Happiness_2019, how="outer", on="Country")
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2018 Generosity,2018 Dystopia Residual,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308

### ReName 2019 Columns

In [366]:
# Rename our 2019 columns
combined_happiness = combined_happiness.rename(columns={"Overall rank":"2019 Happiness Rank", 
                                                        "Score":"2019 Happiness Score", 
                                                        "GDP per capita":"2019 Economy", 
                                                        "Social support": "2019 Family",
                                                        "Healthy life expectancy":"2019 Health", 
                                                        "Freedom to make life choices":"2019 Freedom",
                                                        "Generosity":"2019 Generosity",
                                                        "Perceptions of corruption":"2019 Dystopia Residual"})
combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308

## Checking Merged Data

In [367]:
combined_happiness.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 170 entries, 0 to 169
Data columns (total 45 columns):
Country                   170 non-null object
Region                    164 non-null object
2015 Happiness Rank       158 non-null float64
2015 Happiness Score      158 non-null float64
2015 Economy              158 non-null float64
2015 Family               158 non-null float64
2015 Health               158 non-null float64
2015 Freedom              158 non-null float64
2015 Corruption/Trust     158 non-null float64
2015 Generosity           158 non-null float64
2015 Dystopia Residual    158 non-null float64
2016 Happiness Rank       157 non-null float64
2016 Happiness Score      157 non-null float64
2016 Economy              157 non-null float64
2016 Family               157 non-null float64
2016 Health               157 non-null float64
2016 Freedom              157 non-null float64
2016 Corruption/Trust     157 non-null float64
2016 Generosity           157 non-null float64
2016 Dystopia Residual    157 non-null float64
2017 Happiness Rank       155 non-null float64
2017 Happiness Score      155 non-null float64
2017 Economy              155 non-null float64
2017 Family               155 non-null float64
2017 Health               155 non-null float64
2017 Freedom              155 non-null float64
2017 Corruption/Trust     155 non-null float64
2017 Generosity           155 non-null float64
2017 Dystopia Residual    155 non-null float64
2018 Happiness Rank       156 non-null float64
2018 Happiness Score      156 non-null float64
2018 Economy              156 non-null float64
2018 Family               156 non-null float64
2018 Health               156 non-null float64
2018 Freedom              156 non-null float64
2018 Generosity           156 non-null float64
2018 Dystopia Residual    155 non-null float64
2019 Happiness Rank       156 non-null float64
2019 Happiness Score      156 non-null float64
2019 Economy              156 non-null float64
2019 Family               156 non-null float64
2019 Health               156 non-null float64
2019 Freedom              156 non-null float64
2019 Generosity           156 non-null float64
2019 Dystopia Residual    156 non-null float64
dtypes: float64(43), object(2)
memory usage: 61.1+ KB

### More Happiness Cleaning

In [368]:
# Replace all NaN values with 0 
clean_combined_happiness = combined_happiness.fillna(0)
clean_combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
0,Switzerland,Western Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Western Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Western Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Western Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308

### View Region and Country Names

In [369]:
clean_combined_happiness['Region'].unique()

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia', 0], dtype=object)

In [370]:
clean_combined_happiness['Country'].unique()

array(['Switzerland', 'Iceland', 'Denmark', 'Norway', 'Canada', 'Finland',
       'Netherlands', 'Sweden', 'New Zealand', 'Australia', 'Israel',
       'Costa Rica', 'Austria', 'Mexico', 'United States', 'Brazil',
       'Luxembourg', 'Ireland', 'Belgium', 'United Arab Emirates',
       'United Kingdom', 'Oman', 'Venezuela', 'Singapore', 'Panama',
       'Germany', 'Chile', 'Qatar', 'France', 'Argentina',
       'Czech Republic', 'Uruguay', 'Colombia', 'Thailand',
       'Saudi Arabia', 'Spain', 'Malta', 'Taiwan', 'Kuwait', 'Suriname',
       'Trinidad and Tobago', 'El Salvador', 'Guatemala', 'Uzbekistan',
       'Slovakia', 'Japan', 'South Korea', 'Ecuador', 'Bahrain', 'Italy',
       'Bolivia', 'Moldova', 'Paraguay', 'Kazakhstan', 'Slovenia',
       'Lithuania', 'Nicaragua', 'Peru', 'Belarus', 'Poland', 'Malaysia',
       'Croatia', 'Libya', 'Russia', 'Jamaica', 'North Cyprus', 'Cyprus',
       'Algeria', 'Kosovo', 'Turkmenistan', 'Mauritius', 'Hong Kong',
       'Estonia', 'Indonesia', 'Vietnam', 'Turkey', 'Kyrgyzstan',
       'Nigeria', 'Bhutan', 'Azerbaijan', 'Pakistan', 'Jordan',
       'Montenegro', 'China', 'Zambia', 'Romania', 'Serbia', 'Portugal',
       'Latvia', 'Philippines', 'Somaliland region', 'Morocco',
       'Macedonia', 'Mozambique', 'Albania', 'Bosnia and Herzegovina',
       'Lesotho', 'Dominican Republic', 'Laos', 'Mongolia', 'Swaziland',
       'Greece', 'Lebanon', 'Hungary', 'Honduras', 'Tajikistan',
       'Tunisia', 'Palestinian Territories', 'Bangladesh', 'Iran',
       'Ukraine', 'Iraq', 'South Africa', 'Ghana', 'Zimbabwe', 'Liberia',
       'India', 'Sudan', 'Haiti', 'Congo (Kinshasa)', 'Nepal', 'Ethiopia',
       'Sierra Leone', 'Mauritania', 'Kenya', 'Djibouti', 'Armenia',
       'Botswana', 'Myanmar', 'Georgia', 'Malawi', 'Sri Lanka',
       'Cameroon', 'Bulgaria', 'Egypt', 'Yemen', 'Angola', 'Mali',
       'Congo (Brazzaville)', 'Comoros', 'Uganda', 'Senegal', 'Gabon',
       'Niger', 'Cambodia', 'Tanzania', 'Madagascar',
       'Central African Republic', 'Chad', 'Guinea', 'Ivory Coast',
       'Burkina Faso', 'Afghanistan', 'Rwanda', 'Benin', 'Syria',
       'Burundi', 'Togo', 'Puerto Rico', 'Belize', 'Somalia',
       'Somaliland Region', 'Namibia', 'South Sudan',
       'Taiwan Province of China', 'Hong Kong S.A.R., China',
       'Trinidad & Tobago', 'Northern Cyprus', 'North Macedonia',
       'Gambia'], dtype=object)

### Renaming Region (Names) to match with Protest Data Region Names

In [371]:
clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Western Europe' ] = 'Europe'
clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Eastern Europe' ] = 'Europe'
clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Central and Eastern Europe' ] = 'Europe'

clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Southern Asia' ] = 'Asia'
clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Southeastern Asia' ] = 'Asia'
clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Eastern Asia' ] = 'Asia'

clean_combined_happiness.Region[clean_combined_happiness['Region'] == 'Latin America and Caribbean' ] = 'South America'

clean_combined_happiness.head()

,Country,Region,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,2015 Corruption/Trust,2015 Generosity,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
0,Switzerland,Europe,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Europe,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Europe,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Europe,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308

### Total Happiness & Freedom Score (2015 - 2019)

In [372]:
#---------------"Total Hapiness Score"-----New-----Column------

# Create a new column called "Total Happiness Score" and add up each country's hapiness score per year for our final analysis
clean_combined_happiness["Total Happiness Score"] = clean_combined_happiness["2015 Happiness Score"] + clean_combined_happiness["2016 Happiness Score"] + clean_combined_happiness["2017 Happiness Score"] + clean_combined_happiness["2018 Happiness Score"] + clean_combined_happiness["2019 Happiness Score"]

# Move new column "Total Happiness Score" from end of dataframe & place it next to Region
col_name="Total Happiness Score"
first_col = clean_combined_happiness.pop(col_name)
clean_combined_happiness.insert(2, col_name, first_col)

#---------------"Total Freedom Rate"-----New-----Column------

# Create a new column called "Total Freedom Rate" and add up each country's freedom rate per year for our final analysis
clean_combined_happiness["Total Freedom Rate"] = clean_combined_happiness["2015 Freedom"] + clean_combined_happiness["2016 Freedom"] + clean_combined_happiness["2017 Freedom"] + clean_combined_happiness["2018 Freedom"] + clean_combined_happiness["2019 Freedom"]

# Move new column "Total Freedom Rate" from end of dataframe & place it next to Total Happiness Score
col_name="Total Freedom Rate"
first_col = clean_combined_happiness.pop(col_name)
clean_combined_happiness.insert(3, col_name, first_col)

# Set the index of this new dataframe to be the Country
#clean_combined_happiness = clean_combined_happiness.set_index("Country")

clean_combined_happiness.head()

,Country,Region,Total Happiness Score,Total Freedom Rate,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
0,Switzerland,Europe,37.557,3.103211,1.0,7.587,1.39651,1.34951,0.94143,0.66557,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Europe,37.555,3.090173,2.0,7.561,1.30232,1.40223,0.94784,0.62877,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Europe,37.730,3.129797,3.0,7.527,1.32548,1.36058,0.87464,0.64938,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Europe,37.705,3.190243,4.0,7.522,1.45900,1.33095,0.88521,0.66973,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,36.753,3.054771,5.0,7.427,1.32629,1.32261,0.90563,0.63297,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308

### Assigning Region's Name

In [373]:
# Assigning Values to those countries with no value in thier region column

clean_combined_happiness['Region'] = np.where(
   (clean_combined_happiness['Region'] == 0) & (clean_combined_happiness['Country'] =='Taiwan Province of China') , 'Asia', clean_combined_happiness['Region'])


clean_combined_happiness['Region'] = np.where(
   (clean_combined_happiness['Region'] == 0) & (clean_combined_happiness['Country'] =='Hong Kong S.A.R., China') , 'Asia', clean_combined_happiness['Region'])

clean_combined_happiness['Region'] = np.where(
   (clean_combined_happiness['Region'] == 0) & (clean_combined_happiness['Country'] =='Trinidad & Tobago') , 'South America', clean_combined_happiness['Region'])

clean_combined_happiness['Region'] = np.where(
   (clean_combined_happiness['Region'] == 0) & (clean_combined_happiness['Country'] =='Northern Cyprus') , 'Europe', clean_combined_happiness['Region'])

clean_combined_happiness['Region'] = np.where(
   (clean_combined_happiness['Region'] == 0) & (clean_combined_happiness['Country'] =='North Macedonia') , 'Europe', clean_combined_happiness['Region'])

clean_combined_happiness['Region'] = np.where(
   (clean_combined_happiness['Region'] == 0) & (clean_combined_happiness['Country'] =='Gambia') , 'Sub-Saharan Africa', clean_combined_happiness['Region'])

## Top 10 Happy Countries (2015-2019)

In [374]:
top10 = clean_combined_happiness.head(10)
top10

,Country,Region,Total Happiness Score,Total Freedom Rate,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
0,Switzerland,Europe,37.557,3.103211,1.0,7.587,1.39651,1.34951,0.94143,0.66557,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Europe,37.555,3.090173,2.0,7.561,1.30232,1.40223,0.94784,0.62877,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Europe,37.730,3.129797,3.0,7.527,1.32548,1.36058,0.87464,0.64938,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Europe,37.705,3.190243,4.0,7.522,1.45900,1.33095,0.88521,0.66973,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,36.753,3.054771,5.0,7.427,1.32629,1.32261,0.90563,0.63297,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308
5,Finland,Europe,37.689,3.107681,6.0,7.406,1.29025,1.31826,0.88911,0.64169,...,0.202,0.393,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393
6,Netherlands,Europe,37.023,2.948254,7.0,7.378,1.32944,1.28017,0.89284,0.61576,...,0.333,0.295,5.0,7.488,1.396,1.522,0.999,0.557,0.322,0.298
7,Sweden,Europe,36.596,3.087904,8.0,7.364,1.33171,1.28907,0.91087,0.65980,...,0.285,0.383,7.0,7.343,1.387,1.487,1.009,0.574,0.267,0.373
8,New Zealand,Australia and New Zealand,36.565,3.088912,9.0,7.286,1.25018,1.31967,0.90837,0.63938,...,0.365,0.389,8.0,7.307,1.303,1.557,1.026,0.585,0.330,0.380
9,Australia,Australia and New Zealand,36.381,3.025217,10.0,7.284,1.33358,1.30923,0.93156,0.65124,...,0.361,0.302,11.0,7.228,1.372,1.548,1.036,0.557,0.332,0.290

## Bottom 10 Not so Happy Countries (2015-2019)

In [375]:
bottom10 = clean_combined_happiness.tail(10)
bottom10

,Country,Region,Total Happiness Score,Total Freedom Rate,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
160,Somalia,Sub-Saharan Africa,20.241,2.402907,0.0,0.0,0.0,0.0,0.0,0.0,...,0.238,0.282,112.0,4.668,0.000,0.698,0.268,0.559,0.243,0.270
161,Somaliland Region,Sub-Saharan Africa,5.057,0.391300,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000
162,Namibia,Sub-Saharan Africa,18.228,1.926444,0.0,0.0,0.0,0.0,0.0,0.0,...,0.051,0.064,113.0,4.639,0.879,1.313,0.477,0.401,0.070,0.056
163,South Sudan,Sub-Saharan Africa,13.530,0.465682,0.0,0.0,0.0,0.0,0.0,0.0,...,0.224,0.106,156.0,2.853,0.306,0.575,0.295,0.010,0.202,0.091
164,Taiwan Province of China,Asia,6.422,0.361467,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000
165,"Hong Kong S.A.R., China",Asia,5.472,0.490969,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000
166,Trinidad & Tobago,South America,12.384,1.064000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.171,0.019,39.0,6.192,1.231,1.477,0.713,0.489,0.185,0.016
167,Northern Cyprus,Europe,11.553,0.912000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.179,0.154,64.0,5.718,1.263,1.252,1.042,0.417,0.191,0.162
168,North Macedonia,Europe,5.274,0.345000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,84.0,5.274,0.983,1.294,0.838,0.345,0.185,0.034
169,Gambia,Sub-Saharan Africa,4.516,0.382000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,120.0,4.516,0.308,0.939,0.428,0.382,0.269,0.167

### Created a new dataframe for those countries that had high numbers for Happiness & Freedom

In [376]:
# Create a new dataframe for those countries where "Total Happiness Score" is greater than 30 
# have at least Total Freedom Rate of 2.5
Highest_Happiness_Freedom= clean_combined_happiness.loc[(clean_combined_happiness["Total Happiness Score"] >= 30) &
                                                 (clean_combined_happiness["Total Freedom Rate"] > 2.5)]
                                              
Highest_Happiness_Freedom

,Country,Region,Total Happiness Score,Total Freedom Rate,2015 Happiness Rank,2015 Happiness Score,2015 Economy,2015 Family,2015 Health,2015 Freedom,...,2018 Generosity,2018 Dystopia Residual,2019 Happiness Rank,2019 Happiness Score,2019 Economy,2019 Family,2019 Health,2019 Freedom,2019 Generosity,2019 Dystopia Residual
0,Switzerland,Europe,37.557,3.103211,1.0,7.587,1.39651,1.34951,0.94143,0.66557,...,0.256,0.357,6.0,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,Europe,37.555,3.090173,2.0,7.561,1.30232,1.40223,0.94784,0.62877,...,0.353,0.138,4.0,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,Europe,37.730,3.129797,3.0,7.527,1.32548,1.36058,0.87464,0.64938,...,0.284,0.408,2.0,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,Europe,37.705,3.190243,4.0,7.522,1.45900,1.33095,0.88521,0.66973,...,0.286,0.340,3.0,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,North America,36.753,3.054771,5.0,7.427,1.32629,1.32261,0.90563,0.63297,...,0.321,0.291,9.0,7.278,1.365,1.505,1.039,0.584,0.285,0.308
5,Finland,Europe,37.689,3.107681,6.0,7.406,1.29025,1.31826,0.88911,0.64169,...,0.202,0.393,1.0,7.769,1.340,1.587,0.986,0.596,0.153,0.393
6,Netherlands,Europe,37.023,2.948254,7.0,7.378,1.32944,1.28017,0.89284,0.61576,...,0.333,0.295,5.0,7.488,1.396,1.522,0.999,0.557,0.322,0.298
7,Sweden,Europe,36.596,3.087904,8.0,7.364,1.33171,1.28907,0.91087,0.65980,...,0.285,0.383,7.0,7.343,1.387,1.487,1.009,0.574,0.267,0.373
8,New Zealand,Australia and New Zealand,36.565,3.088912,9.0,7.286,1.25018,1.31967,0.90837,0.63938,...,0.365,0.389,8.0,7.307,1.303,1.557,1.026,0.585,0.330,0.380
9,Australia,Australia and New Zealand,36.381,3.025217,10.0,7.284,1.33358,1.30923,0.93156,0.65124,...,0.361,0.302,11.0,7.228,1.372,1.548,1.036,0.557,0.332,0.290
11,Costa Rica,South America,35.631,2.956142,12.0,7.226,0.95578,1.23788,0.86027,0.63376,...,0.143,0.101,12.0,7.167,1.034,1.441,0.963,0.558,0.144,0.093
12,Austria,Europe,35.710,2.884646,13.0,7.200,1.33723,1.29704,0.89042,0.62433,...,0.242,0.224,10.0,7.246,1.376,1.475,1.016,0.532,0.244,0.226
14,United States,North America,34.994,2.534411,15.0,7.119,1.39451,1.24711,0.86179,0.54604,...,0.291,0.133,19.0,6.892,1.433,1.457,0.874,0.454,0.280,0.128
16,Luxembourg,Europe,34.680,2.919158,17.0,6.946,1.56391,1.21963,0.91894,0.61583,...,0.196,0.321,14.0,7.090,1.609,1.479,1.012,0.526,0.194,0.316
17,Ireland,Europe,34.822,2.860960,18.0,6.940,1.33596,1.36948,0.89533,0.61777,...,0.307,0.306,16.0,7.021,1.499,1.553,0.999,0.516,0.298,0.310
18,Belgium,Europe,34.607,2.693811,19.0,6.937,1.30782,1.28566,0.89667,0.58450,...,0.188,0.240,18.0,6.923,1.356,1.504,0.986,0.473,0.160,0.210
19,United Arab Emirates,Middle East and Northern Africa,33.721,2.694065,20.0,6.901,1.42727,1.12575,0.80925,0.64157,...,0.186,0.000,21.0,6.825,1.503,1.310,0.825,0.598,0.262,0.182
20,United Kingdom,Europe,34.550,2.518800,21.0,6.867,1.26637,1.28548,0.90943,0.59625,...,0.262,0.082,15.0,7.054,1.333,1.538,0.996,0.450,0.348,0.278
23,Singapore,Asia,32.714,2.767061,24.0,6.798,1.52186,1.02000,1.02525,0.54252,...,0.261,0.457,34.0,6.262,1.572,1.463,1.141,0.556,0.271,0.453
24,Panama,South America,32.690,2.694397,25.0,6.786,1.06353,1.19850,0.79661,0.54210,...,0.125,0.063,31.0,6.321,1.149,1.442,0.910,0.516,0.109,0.054
25,Germany,Europe,34.645,2.792941,26.0,6.750,1.32792,1.29937,0.89186,0.61477,...,0.273,0.280,17.0,6.985,1.373,1.454,0.987,0.495,0.261,0.265
27,Qatar,Middle East and Northern Africa,32.109,3.020321,28.0,6.611,1.69042,1.07860,0.79733,0.64040,...,0.256,0.171,29.0,6.374,1.684,1.313,0.871,0.555,0.220,0.167
31,Uruguay,South America,32.156,2.874892,32.0,6.485,1.06166,1.20890,0.81160,0.60362,...,0.130,0.155,33.0,6.293,1.124,1.465,0.891,0.523,0.127,0.150
33,Thailand,Asia,31.433,2.826371,34.0,6.455,0.96690,1.26504,0.73850,0.55664,...,0.364,0.029,52.0,6.008,1.050,1.409,0.828,0.557,0.359,0.028
36,Malta,Europe,32.670,2.951357,37.0,6.302,1.20740,1.30203,0.88721,0.60365,...,0.376,0.142,22.0,6.726,1.300,1.520,0.999,0.564,0.375,0.151
38,Kuwait,Middle East and Northern Africa,30.743,2.529988,39.0,6.295,1.55422,1.16594,0.72492,0.55499,...,0.167,0.106,51.0,6.021,1.500,1.319,0.808,0.493,0.142,0.097
42,Guatemala,South America,31.719,2.751431,43.0,6.123,0.74553,1.04356,0.64425,0.57733,...,0.179,0.071,27.0,6.436,0.800,1.269,0.746,0.535,0.175,0.078
43,Uzbekistan,Europe,30.231,3.279939,44.0,6.003,0.63244,1.34043,0.59772,0.65821,...,0.328,0.259,41.0,6.174,0.745,1.529,0.756,0.631,0.322,0.240
48,Bahrain,Middle East and Northern Africa,30.569,2.595417,49.0,5.960,1.32376,1.21624,0.74716,0.45492,...,0.243,0.123,37.0,6.199,1.362,1.368,0.871,0.536,0.255,0.110

#### Export & Save Data
* Export the merged, cleaned world happiness data into a .csv.

In [377]:
# Export DataFrame & Save DataFrame to a .CSV
clean_combined_happiness.to_csv('Happiness_Data/clean_combined_happiness.csv')